import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import SalesPage from '@/components/SalesPage'
import UpsellModal from '@/components/UpsellModal'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sales Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <UpsellModal />
        <SalesPage />
      </main>
    </>
  )
}
